### ISSUE TITLE
出现undefined symbol：PyFPE_jbuf 问题

### ISSUE THREAD

**Issue by zhujunwen** [choasUp/SIN#9]
当我运行demo.py 和 train.sh时都会出现，请问是什么原因？
Traceback (most recent call last):
  File "demo.py", line 3, in <module>
    from fast_rcnn.config import cfg
  File "/home/home_data/zjw/SIN/SIN/tools/../lib/fast_rcnn/__init__.py", line 10, in <module>
    from . import test
  File "/home/home_data/zjw/SIN/SIN/tools/../lib/fast_rcnn/test.py", line 6, in <module>
    from utils.cython_nms import nms, nms_new
ImportError: /home/home_data/zjw/SIN/SIN/tools/../lib/utils/cython_nms.so: undefined symbol: PyFPE_jbuf

**Comment by choasup** [comment]
you can try

```
cd $SIN_ROOT/lib
make
```
